### ISSUE TITLE
Wikipedia ‘Edit’ and ‘History’ links broken

### ISSUE THREAD

**Issue by Smylers** [ronhasson/WikiWand-webextension#2]
Hi. Thanks for this extension — I'd been missing this functionality since upgrading Firefox a few weeks ago.

Unfortunately it's a little over-eager to redirect Wikipedia URLs to Wikiwand: it catches some links from Wikiwand that are supposed to go to Wikipedia pages.

To reproduce:

1. View an article on Wikiwand. I chose [Ilkley](https://www.wikiwand.com/en/Ilkley).
2. Click on the ‘W’ icon at the top, to open the ‘Wikipedia Tools’ menu.
3. Hover the mouse pointer over the ‘edit’ menu item. Note that the URL is something like: https://en.wikipedia.org/w/index.php?title=Ilkley&action=edit
4. Click on that menu item. It opens a new tab. The extension intercepts that URL and you end up at the Wikiwand page: https://www.wikiwand.com/en/Webserver_directory_index?title=Ilkley&action=edit (where the URL parameters are ignored, so it's simply viewing the article called ‘Webserver directory index’ — who even knew there was such an article?).

There's an equivalent problem with the ‘History’ link just below ‘Edit’.

Please can you narrow down the intercepting to ignore URLs like these. Perhaps just ignore everything with a URL parameter of `action=`? (You could make an exception for `action=view`, but with normal browsing you shouldn't end up with a URL with that in it anyway (since viewing is the default action), so ignoring all `action=` params may be simpler.) Thanks.

**Comment by ronhasson** [comment]
yup, I can fix this, I can ignore all `action=` like I ignore the `oldformat` parameters.
meanwhile, you can use the extension button near the top right to disable and enable the addon quickly, but the fix shouldn't take long.
