### ISSUE TITLE
Re-enabling doesn't work until restarting Firefox

### ISSUE THREAD

**Issue by Smylers** [ronhasson/WikiWand-webextension#3]
If this extension is disabled in `about:addons`, enabling it again doesn't have any effect until Firefox is restarted.

To reproduce:

1. Have this WikiWand extension installed and enabled.
2. Go to a Wikipedia URL. I chose [List of animals with fraudulent diplomas](https://en.wikipedia.org/wiki/List_of_animals_with_fraudulent_diplomas). See that this extension intercepts that URL and redirects you to Wikiwand, as intended.
3. Go to `about:addons`, find ‘WikiWand webextension’ and press ‘Disable’.
4. Go the the Wikipedia URL again. This time it should remain on Wikipedia: disabling the extension has worked immediately.
5. Return to `about:addons’ and re-enable the extension.
6. Try the Wikipedia URL again. Unfortunately it remains on Wikipedia: re-enabling the extension hasn't worked.
7. Restart Firefox.
8. Give the Wikipedia URL one last go. Now it's intercepting properly again; restarting Firefox seems to've made the extension work again.

This is unfortunate because the workaround for Issue #2 is to temporarily disable the extension in order to edit a Wikipedia page ... but ’temporarily’ ends up meaning I'm without this extension until I'm next restarting Firefox.

**Comment by ronhasson** [comment]
I'll look into that, maybe I can do something about this.
Are you on the latest version(0.3)? you are supposed to have an icon near the top left that says "enable/disable wikiwand", which will let you disable the redirect as long as you want without going to `about:addons`

**Comment by Smylers** [comment]
Yes, 0.3.

Sorry, I'd forgotten about the button. I must've removed it after installing the extension, thinking it was clutter I wouldn't need (“Why would I ever want to disable this extension?”) then completely forgot about it when I did need it.

Thanks.

**Comment by ronhasson** [comment]
This is a problem on Firefox's end. I can't even work around that issue, and since we already have an alternative (the addon icon), I'm closing this issue.
