### ISSUE TITLE
What's the future?

### ISSUE THREAD

**Issue by talha131** [ronhasson/WikiWand-webextension#5]
Thank your Ron for creating this add-on even before official WikiWand add-on was ported to web extensions API. I appreciate how your proactively created this replacement instead of waiting for update from WikiWand guys.

Now that an official WikiWand add-on that supports web extensions API has been released on Nov 19, 2017, what are your plans? Will you keep supporting this add-on?

**Comment by ronhasson** [comment]
Did they? thanks for letting me know.
Now I'm looking at their code and I think it's kinda bloated.

I want to say that as long as I can, I will continue to support this addon and I will still use it myself.

As long as the devs of Wikiwand won't reach out to me to remove this addon for some legal issue or some other reason, this addon will stay in the AMO.

As for right now, I know the chrome version of the addon have google analytics bundled with it (and the current web extension version for Firefox doesn't), where I can promise my addon will never have.

Lastly, as for the current state of *my* version of the addon, its mostly finished and should work as expected. the only other feature that I can think of that I want to add is a low priority feature that is only nice to have in small use cases (convert the page back to Wikipedia when the addon's button is disabled, with an options page to enable or disable this of course)

**Comment by talha131** [comment]
Thank you Ron. I too will continue using it.
