### ISSUE TITLE
Read on Wikipedia does not work

### ISSUE THREAD

**Issue by talha131** [ronhasson/WikiWand-webextension#6]
Clicking on "Read on Wikipedia" opens a new tab to wikipedia but is soon redirected to wikiwand.U

I tested on Firefox Developer Edition 58.0b12 (64-bit).

Apparently `?oldformat=true` in the URL is not honored.

**Comment by ronhasson** [comment]
Huh. So apparently after I fixed problem #4 and merging elegantly all the Wikipedia tools together in the code, I accidentally also deleted the line that checks for ?oldformat [(the commit)](https://github.com/ronhasson/WikiWand-webextension/commit/0f0ef8b63380f243bfd9d0f9192331482a119311 )

I will provide a fix soon :)
